Repository roboflow/supervision, pull requests merged in 2023-10, with the labels that each got.

#384 docs: 📝 code of conduct added
  CODE_OF_CONDUCT.md
Labels: documentation

#386 feat(annotator): 🚀 introduce circle annotator
  docs/detection/annotate.md
  supervision/__init__.py
  supervision/annotators/core.py
Labels: documentation, enhancement, version: 0.15.0, api:annotator, hacktoberfest, hacktoberfest-accepted

#392 Refactor documentation structure and improve annotator details
  docs/annotators.md
  docs/datasets.md
  docs/detection/annotate.md
  docs/trackers.md
  mkdocs.yml
  supervision/annotators/core.py
Labels: documentation, enhancement

#400 Add email to Code of Conduct
  CODE_OF_CONDUCT.md
Labels: documentation

#399 Remove class list dependency for roboflow to detection conversion
  supervision/detection/core.py
  supervision/detection/utils.py
  test/detection/test_utils.py
Labels: version: 0.15.0, hacktoberfest, hacktoberfest-accepted

#406 Refactor TraceAnnotator to separate utility class
  docs/annotators.md
  supervision/__init__.py
  supervision/annotators/base.py
  supervision/annotators/core.py
  supervision/annotators/utils.py
  supervision/detection/annotate.py
  test/annotators/test_utils.py
Labels: enhancement, api:annotator

#407 Add color mapping strategy to InferenceSlicer
  supervision/annotators/core.py
Labels: enhancement, version: 0.15.0, api:annotator

#405 Create sv.BlurAnnotator #395
  supervision/__init__.py
  supervision/annotators/core.py
Labels: enhancement, api:annotator, hacktoberfest, hacktoberfest-accepted

#404 `supervision-0.15.0` release
  .github/workflows/test.yml
  .pre-commit-config.yaml
  CODE_OF_CONDUCT.md
  README.md
  docs/annotators.md
  docs/changelog.md
  docs/datasets.md
  docs/detection/annotate.md
  docs/geometry/core.md
  docs/trackers.md
  examples/tracking/script.py
  examples/traffic_analysis/.gitignore
  examples/traffic_analysis/README.md
  examples/traffic_analysis/requirements.txt
  examples/traffic_analysis/script.py
  examples/traffic_analysis/script.sh
  mkdocs.yml
  poetry.lock
  pyproject.toml
  supervision/__init__.py
  supervision/annotators/__init__.py
  supervision/annotators/base.py
  supervision/annotators/core.py
  supervision/annotators/utils.py
  supervision/detection/annotate.py
  supervision/detection/core.py
  supervision/detection/tools/inference_slicer.py
  supervision/detection/tools/polygon_zone.py
  supervision/detection/utils.py
  supervision/geometry/core.py
  supervision/utils/video.py
  test/annotators/__init__.py
  test/annotators/test_utils.py
  test/detection/test_core.py
  test/detection/test_utils.py
Labels: version: 0.15.0

#416 Supervision demo notebook fix and yolo-nas fix
  .pre-commit-config.yaml
  demo.ipynb
  supervision/detection/core.py
Labels: bug

#424 add #a351fb as first default color into sv.draw.color.ColorPalette
  supervision/draw/color.py
Labels: enhancement, version: 0.16.0, hacktoberfest, hacktoberfest-accepted

#425 Add Discord button to README
  README.md
Labels: documentation

#426 faster sv.MaskAnnotator
  supervision/annotators/core.py
Labels: enhancement, version: 0.16.0, api:annotator, hacktoberfest

#280 Feature FPS meaure
  docs/utils/fps.md
  mkdocs.yml
  supervision/__init__.py
  supervision/utils/fps.py
Labels: enhancement, priority:high, hacktoberfest, hacktoberfest-accepted

#411 fix(import): 🐞 add ColorMap into init.py
  supervision/__init__.py
Labels: enhancement

#430 Fix return value when sv.Detections is empty
  supervision/tracker/byte_tracker/core.py
Labels: enhancement, hacktoberfest, api:tracker

#432 Move FpsMonitor from utils to video module
  docs/utils/fps.md
  docs/utils/video.md
  mkdocs.yml
  supervision/__init__.py
  supervision/utils/fps.py
  supervision/utils/video.py
Labels: enhancement, api: video

#422 Added box mask annotators
  docs/annotators.md
  supervision/__init__.py
  supervision/annotators/core.py
Labels: enhancement, api:annotator, hacktoberfest, hacktoberfest-accepted

#440 chore: :fire: delete redundant Makefile because pypi and formatters are automatic.
  Makefile
Labels: enhancement, version: 0.16.0

#436 #418 Make sv.ByteTrack work with segmentation model
  supervision/tracker/byte_tracker/core.py
Labels: version: 0.16.0, hacktoberfest, hacktoberfest-accepted, api:tracker

#437 Update sv.Detections.from_roboflow to extract tracker_id values from inference response
  supervision/detection/core.py
  supervision/detection/utils.py
  test/detection/test_utils.py
Labels: enhancement, version: 0.16.0, hacktoberfest, hacktoberfest-accepted

#448 chore: 🔥 remove duplicate isort from pre-commit-config
  .pre-commit-config.yaml
Labels: enhancement, dependencies

#454 Adding HuggingFace Annotators Space link to `README.md`
  README.md
Labels: documentation, version: 0.16.0, hacktoberfest, hacktoberfest-accepted

#344 Adding example and example guidelines
  examples/README.md
  pyproject.toml
Labels: documentation, version: 0.16.0, api:examples

#457 ci: 🚧 github action - python cache added 🚀
  .github/requirements-dev.txt
  .github/workflows/clear-cache.yml
  .github/workflows/test.yml
Labels: enhancement, dependencies

#469 docs: 📓 development virtualenv installation pip upgrade added
  docs/index.md
Labels: bug, documentation, enhancement

#465 Update color mapping system in detection annotations
  supervision/__init__.py
  supervision/annotators/core.py
  supervision/annotators/utils.py
  test/annotators/test_utils.py
Labels: enhancement, api:annotator

#483 Add 404 page
  custom_theme/404.html
  mkdocs.yml
Labels: bug, documentation, version: 0.16.0

#482 Linezone.trigger returns bool nparray
  supervision/detection/line_counter.py
Labels: enhancement, api: linezone, hacktoberfest, hacktoberfest-accepted

#490 Add documentation and improvements to "LineZone" functionality
  docs/detection/tools/line_zone.md
  mkdocs.yml
  supervision/detection/line_counter.py
Labels: enhancement, api: linezone

#492 Create sv.dot marker annotator #396
  supervision/__init__.py
  supervision/annotators/core.py
Labels: enhancement, api:annotator, hacktoberfest

#496 Expand and update `Color`, `ColorPalette`, and `DotAnnotator` classes
  docs/annotators.md
  docs/draw/color.md
  mkdocs.yml
  supervision/annotators/core.py
  supervision/annotators/utils.py
  supervision/draw/color.py
Labels: documentation, enhancement, version: 0.16.0, api:annotator

#489 Add How to Detect and Annotate guide
  docs/how_to/detect_and_annotate.md
Labels: documentation, hacktoberfest

#466 New feature HeatmapAnnotator
  supervision/annotators/core.py
Labels: enhancement, version: 0.16.0, api:annotator, hacktoberfest, hacktoberfest-accepted

#498 Add HeatMapAnnotator class to supervision
  docs/annotators.md
  supervision/__init__.py
  supervision/annotators/core.py
Labels: documentation, enhancement, version: 0.16.0, api:annotator, hacktoberfest

#449 feat: 🚀 Enable Watermarking images and videos
  supervision/draw/utils.py
Labels: enhancement, version: 0.16.0, api:annotator, hacktoberfest

#501 Remove custom 404 page and update documentation for new release
  custom_theme/404.html
  docs/changelog.md
  mkdocs.yml
  pyproject.toml
Labels: documentation, version: 0.16.0

#493 `supervision-0.16.0` release
  .github/requirements-dev.txt
  .github/workflows/clear-cache.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  Makefile
  README.md
  demo.ipynb
  docs/annotators.md
  docs/changelog.md
  docs/detection/tools/line_zone.md
  docs/draw/color.md
  docs/draw/utils.md
  docs/how_to/detect_and_annotate.md
  docs/how_to/evaluate_model.md
  docs/how_to/filter_detections.md
  docs/how_to/process_video.md
  docs/how_to/track_objects.md
  docs/index.md
  docs/utils/video.md
  examples/README.md
  mkdocs.yml
  poetry.lock
  pyproject.toml
  supervision/__init__.py
  supervision/annotators/core.py
  supervision/annotators/utils.py
  supervision/classification/core.py
  supervision/dataset/core.py
  supervision/detection/core.py
  supervision/detection/line_counter.py
  supervision/detection/utils.py
  supervision/draw/color.py
  supervision/draw/utils.py
  supervision/tracker/byte_tracker/core.py
  supervision/utils/video.py
  test/annotators/test_utils.py
  test/detection/test_utils.py
Labels: version: 0.16.0

#510 fix(notebook): 🐛📘 sam detection ColorLookup param and enum added and sv version updated
  demo.ipynb
Labels: bug, documentation, api:examples

#476 feat(assets): ✨ assets and assets downloader add-on for supervision[assets]
  docs/assets.md
  mkdocs.yml
  poetry.lock
  pyproject.toml
  supervision/assets/__init__.py
  supervision/assets/downloader.py
  supervision/assets/list.py
Labels: documentation, enhancement, dependencies, version: 0.17.0

#552 Add Kapa documentation bot to supervision docs
  docs/javascript/init_kapa_widget.js
  mkdocs.yml
Labels: documentation

#558 Update init_kapa_widget.js
  docs/javascript/init_kapa_widget.js
Labels: bug, documentation

#555 fix: #540 bug blur annotator
  supervision/annotators/core.py
  supervision/detection/tools/polygon_zone.py
  supervision/detection/utils.py
  test/detection/test_utils.py
Labels: bug, api:annotator
