Repository roboflow/supervision, pull requests merged in 2023-07, with the labels that each got.

#176 🛠️ fix incorrect COCO class id loading
  supervision/dataset/formats/coco.py
  test/dataset/formats/test_coco.py
Labels: version: 0.12.0

#192 Fixing empty detection coco dataset
  supervision/dataset/utils.py
  test/dataset/test_utils.py
Labels: version: 0.12.0

#180 Introduce pyproject toml file with optional install method and dropping python 3.7 support
  .github/workflows/publish.yml
  .github/workflows/test.yml
  Makefile
  README.md
  poetry.lock
  pyproject.toml
  setup.py
  supervision/__init__.py
Labels: version: 0.12.0

#177 Add ConfusionMatrix to EvaluationAPI
  docs/metrics/detection.md
  mkdocs.yml
  supervision/__init__.py
  supervision/metrics/__init__.py
  supervision/metrics/detection.py
  test/metrics/__init__.py
  test/metrics/test_detection.py
  test/utils.py
Labels: version: 0.12.0

#159 Add unicode label support
  setup.py
  supervision/detection/annotate.py
Labels: version: 0.12.0

#207 chore: ✨ update github action versions (actions/checkout@v3, actions/setup-python@v4)
  .github/workflows/docs.yml
Labels: documentation, enhancement, version: 0.12.0

#214 docs: 📝 update installation and source installation methods
  README.md
  docs/index.md
Labels: documentation

#217 🛠️ fix `detections_to_tensor`
  supervision/metrics/detection.py
  test/metrics/test_detection.py
Labels: bug, version: 0.12.0

#219 fix: 🐛 package version control if PackageNotFoundError occured
  supervision/__init__.py
Labels: bug

#220 docs: 📝 Update python version for supervision version 0.12.0
  docs/index.md
  pyproject.toml
Labels: documentation

#218 feat: 🛠 adding python dev tools into toml file
  .github/workflows/docs.yml
  .github/workflows/test.yml
  poetry.lock
  pyproject.toml
Labels: bug, version: 0.12.0

#226 Fix yolo dataset background instance loading
  supervision/dataset/formats/yolo.py
Labels: bug

#223 🛠️ #212 bug fix
  supervision/dataset/formats/yolo.py
  supervision/metrics/detection.py
Labels: bug, version: 0.12.0

#208 Add 0.12.0 changelog
  docs/changelog.md
Labels: documentation, version: 0.12.0

#171 cornered box annotator
  setup.py
  supervision/__init__.py
  supervision/annotators/composable.py
  supervision/annotators/core.py
  supervision/detection/core.py
  supervision/geometry/core.py
  test/dataset/test_core.py
  test/detection/test_core.py
Labels: version: 0.12.0

#225 Format coco output data as per standard
  supervision/dataset/formats/coco.py
Labels: bug, version: 0.13.0

#237 docs: 📝 MIT license classifier added
  pyproject.toml
Labels: bug, version: 0.13.0

#229 Contributing guidelines added for colab request
  CONTRIBUTING.md
Labels: documentation, version: 0.13.0

#191 Paddledet support
  supervision/detection/core.py
Labels: version: 0.13.0

#222 Feature/ultralytics all models
  supervision/detection/core.py
  supervision/detection/utils.py
Labels: enhancement, version: 0.13.0

#245 Add support for loading segmentation datasets in Pascal VOC format
  supervision/dataset/core.py
  supervision/dataset/formats/pascal_voc.py
  supervision/detection/utils.py
  test/dataset/formats/test_pascal_voc.py
Labels: enhancement, api: datasets, version: 0.13.0
