Repository roboflow/supervision, pull requests merged in 2023-06, with the labels that each got.

#118 feature/115_how_to_select_detections_by_index
  supervision/detection/core.py
  test/detection/test_core.py
Labels: enhancement, 0.9.0

#101 Adding yolov8 masks to detections
  supervision/detection/core.py
Labels: enhancement

#120 feature/new_video_utils
  README.md
  docs/image.md
  docs/index.md
  mkdocs.yml
  setup.py
  supervision/__init__.py
  supervision/detection/core.py
  supervision/detection/utils.py
  supervision/image.py
  supervision/video.py
Labels: enhancement, 0.9.0

#125 Add ClassificationDataset API
  CITATION.cff
  docs/classification/core.md
  docs/dataset/core.md
  mkdocs.yml
  supervision/__init__.py
  supervision/classification/__init__.py
  supervision/classification/core.py
  supervision/dataset/core.py
  test/classification/__init__.py
  test/classification/test_core.py
Labels: enhancement

#110 Add semantic segmentation polygon loading from Roboflow
  supervision/detection/core.py
  supervision/detection/utils.py
  test/detection/test_utils.py
Labels: enhancement

#162 video generator with start and end position feature
  supervision/dataset/core.py
  supervision/dataset/formats/coco.py
  supervision/utils/video.py
Labels: enhancement, version: 0.11.0, api: video

#161 `0.11.0` release
  CITATION.cff
  README.md
  docs/changelog.md
  supervision/__init__.py
Labels: version: 0.11.0

#165 Fix top_k processing in as_folder_structure
  supervision/dataset/core.py
Labels: bug
