Repository roboflow/supervision, pull requests merged in 2023-12, with the labels that each got.

#637 dynamic font scale and line thickness calculation based on image resolution
  docs/draw/utils.md
  supervision/__init__.py
  supervision/draw/utils.py
Labels: enhancement

#639 Add mkdocs-material[imaging] dependency
  .github/workflows/docs.yml
Labels: documentation

#643 Add open graph images to documentation.
  docs/assets/supervision-lenny.png
  mkdocs.yml
Labels: documentation

#633 Add `PixelateAnnotator`
  docs/annotators.md
  supervision/__init__.py
  supervision/annotators/core.py
Labels: api:annotator

#647 fix(format): 🐞 removal of numpy,matplotlib,pillow max versions for flexible to collab updates
  pyproject.toml
Labels: bug, dependencies

#648 fix(versions): 🐞 min numpy version changed to 1.21.2
  .github/requirements-dev-min.txt
  pyproject.toml
Labels: bug, dependencies, bug:collab

#651 Add `scale_boxes` function to detection utils
  docs/detection/utils.md
  supervision/__init__.py
  supervision/detection/utils.py
  test/detection/test_utils.py
Labels: enhancement, version: 0.17.0

#511 Fixed TraceAnnotator to respect the postion argument.
  supervision/annotators/core.py
Labels: bug

#652 Add `TriangleAnnotator` to annotators
  docs/annotators.md
  supervision/__init__.py
  supervision/annotators/core.py
Labels: enhancement, api:annotator

#659 feat: ✨ Python 3.12 support added
  .github/requirements-dev.txt
  .github/workflows/test.yml
  README.md
  docs/index.md
  poetry.lock
  pyproject.toml
Labels: dependencies, python

#660 fix(examples): 🐞 tracking LabelAnnotator and traffic_analysis deps fixed
  demo.ipynb
  examples/tracking/README.md
  examples/tracking/script.py
  examples/traffic_analysis/requirements.txt
Labels: bug, api:examples

#665 feat(xml-parsing): 🔐 enhance security with defusedxml and bandit rules
  .github/requirements-dev-min.txt
  poetry.lock
  pyproject.toml
  supervision/dataset/formats/pascal_voc.py
  test/dataset/formats/test_pascal_voc.py
Labels: api:security

#666 feat(tox): ✨ initial tox.ini for testing multiple python versions locally for supervision
  poetry.lock
  pyproject.toml
  tox.ini
Labels: enhancement, dependencies, python

#671 fix(sec-md5): 🐞 md5 security warning fix
  supervision/assets/downloader.py
Labels: api:security

#673 example/count_people_in_zone
  examples/README.md
  examples/count_people_in_zone/.gitignore
  examples/count_people_in_zone/README.md
  examples/count_people_in_zone/data/horizontal-zone-config.json
  examples/count_people_in_zone/data/multi-zone-config.json
  examples/count_people_in_zone/data/quarters-zone-config.json
  examples/count_people_in_zone/data/vertical-zone-config.json
  examples/count_people_in_zone/requirements.txt
  examples/count_people_in_zone/script.py
  examples/count_people_in_zone/setup.sh
  examples/tracking/README.md
  examples/traffic_analysis/README.md
Labels: api:examples

#680 adding heatmap example
  examples/README.md
  examples/heatmap_and_track/README.md
  examples/heatmap_and_track/requirements.txt
  examples/heatmap_and_track/script.py
Labels: enhancement, api:examples

#701 fix(md5): 🐞 hash_new param fix for downloaded content check
  supervision/assets/downloader.py
Labels: bug
