Repository roboflow/supervision, pull requests merged in 2023-09, with the labels that each got.

#354 example/traffic_analysis
  docs/detection/annotate.md
  examples/traffic_analysis/.gitignore
  examples/traffic_analysis/README.md
  examples/traffic_analysis/requirements.txt
  examples/traffic_analysis/script.py
  examples/traffic_analysis/script.sh
  supervision/__init__.py
  supervision/detection/annotate.py
  supervision/detection/core.py
  supervision/detection/tools/polygon_zone.py
Labels: version: 0.15.0, api:examples

#349 fix: 🐛 Empty check for xyxy results for prevent ValueError and return as empty detection
  supervision/detection/core.py
Labels: bug

#381 Adding Fourcc codecs option to VideoSink
  supervision/utils/video.py
Labels: enhancement

#382 add sahi paper url into docstring
  supervision/detection/tools/inference_slicer.py
Labels: documentation

#170 redesigned annotators
  docs/detection/annotate.md
  docs/geometry/core.md
  examples/tracking/script.py
  examples/traffic_analysis/requirements.txt
  supervision/__init__.py
  supervision/annotators/__init__.py
  supervision/annotators/base.py
  supervision/annotators/core.py
  supervision/detection/annotate.py
  supervision/detection/core.py
  supervision/geometry/core.py
  test/annotators/__init__.py
  test/annotators/test_base.py
  test/detection/test_core.py
Labels: version: 0.12.0, version: 0.13.0, version 0.14.0, version: 0.15.0
