Repository roboflow/supervision, pull requests merged in 2023-08, with the labels that each got.

#262 Update core.py (n, W, H) -> (n, H, W)
  supervision/detection/core.py
Labels: bug, version: 0.13.0

#236 Feature MeanAveragePrecision 🔥
  docs/metrics/detection.md
  supervision/__init__.py
  supervision/metrics/detection.py
  test/metrics/test_detection.py
  test/utils.py
Labels: enhancement, version: 0.13.0

#270 🧹 small cleanup
  supervision/detection/core.py
  supervision/metrics/detection.py
Labels: documentation, enhancement, version: 0.13.0

#256 Tracker latest
  docs/tracker/core.md
  mkdocs.yml
  poetry.lock
  pyproject.toml
  supervision/__init__.py
  supervision/tracker/__init__.py
  supervision/tracker/byte_tracker/__init__.py
  supervision/tracker/byte_tracker/basetrack.py
  supervision/tracker/byte_tracker/core.py
  supervision/tracker/byte_tracker/kalman_filter.py
  supervision/tracker/byte_tracker/matching.py
  supervision/utils/video.py
Labels: version: 0.13.0

#273 ultralytics tracker support added
  supervision/detection/core.py
Labels: enhancement, version: 0.13.0

#274 v0.13.0 changelog
  docs/changelog.md
Labels: documentation, version: 0.13.0

#272 🤩 `supervision-0.13.0` release
  CONTRIBUTING.md
  README.md
  docs/changelog.md
  docs/metrics/detection.md
  docs/tracker/core.md
  mkdocs.yml
  poetry.lock
  pyproject.toml
  supervision/__init__.py
  supervision/dataset/core.py
  supervision/dataset/formats/coco.py
  supervision/dataset/formats/pascal_voc.py
  supervision/dataset/formats/yolo.py
  supervision/detection/core.py
  supervision/detection/utils.py
  supervision/metrics/detection.py
  supervision/tracker/__init__.py
  supervision/tracker/byte_tracker/__init__.py
  supervision/tracker/byte_tracker/basetrack.py
  supervision/tracker/byte_tracker/core.py
  supervision/tracker/byte_tracker/kalman_filter.py
  supervision/tracker/byte_tracker/matching.py
  supervision/utils/video.py
  test/dataset/formats/test_pascal_voc.py
  test/metrics/test_detection.py
  test/utils.py
Labels: version: 0.13.0

#241 feat: 🚀 pre-commit and formatted files
  .gitattributes
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/feature-request.yml
  .github/ISSUE_TEMPLATE/question.yml
  .github/workflows/test.yml
  .github/workflows/welcome.yml
  .pre-commit-config.yaml
  CITATION.cff
  CONTRIBUTING.md
  Makefile
  README.md
  demo.ipynb
  docs/changelog.md
  docs/dataset/core.md
  docs/detection/annotate.md
  docs/detection/tools/polygon_zone.md
  docs/detection/utils.md
  docs/draw/utils.md
  docs/index.md
  docs/metrics/detection.md
  docs/quickstart/detections.md
  docs/stylesheets/extra.css
  docs/tracker/core.md
  docs/utils/image.md
  docs/utils/notebook.md
  docs/utils/video.md
  mkdocs.yml
  pyproject.toml
  supervision/classification/core.py
  supervision/dataset/core.py
  supervision/dataset/formats/pascal_voc.py
  supervision/dataset/formats/yolo.py
  supervision/dataset/utils.py
  supervision/detection/annotate.py
  supervision/detection/core.py
  supervision/detection/line_counter.py
  supervision/detection/tools/polygon_zone.py
  supervision/detection/utils.py
  supervision/draw/color.py
  supervision/draw/utils.py
  supervision/geometry/utils.py
  supervision/metrics/detection.py
  supervision/tracker/byte_tracker/core.py
  supervision/tracker/byte_tracker/kalman_filter.py
  supervision/utils/file.py
  supervision/utils/image.py
  supervision/utils/notebook.py
  supervision/utils/video.py
  test/classification/test_core.py
  test/dataset/formats/test_coco.py
  test/dataset/formats/test_pascal_voc.py
  test/dataset/formats/test_yolo.py
  test/dataset/test_core.py
  test/dataset/test_utils.py
  test/detection/test_core.py
  test/detection/test_utils.py
  test/geometry/test_dataclasses.py
  test/metrics/test_detection.py
Labels: enhancement, version: 0.13.0, version 0.14.0

#277 tracer in consistent format
  supervision/__init__.py
  supervision/annotators/core.py
Labels: version 0.14.0

#286 docs: 📝 typo fix for PaddleDetection in args
  docs/changelog.md
  supervision/detection/core.py
  supervision/tracker/byte_tracker/core.py
Labels: documentation

#281 Feature/ultralytics all models for Classification
  supervision/classification/core.py
  supervision/detection/core.py
Labels: version 0.14.0

#288 Update CONTRIBUTING.md file
  CONTRIBUTING.md
Labels: documentation, version 0.14.0

#301 fix(docs): 📚🐛 deprecated for "from_yolov8" desc fix for detection
  supervision/detection/core.py
Labels: documentation

#300 Fix issue #299
  supervision/detection/utils.py
  test/detection/test_utils.py
Labels: bug, version 0.14.0

#307 ci: :green_heart: pre-commit autoupdate
  .pre-commit-config.yaml
Labels: dependencies

#314 Fix SAM video URL on README
  README.md
Labels: documentation

#318 docs: 📝 code quality duplication removal and improvement in current
  CONTRIBUTING.md
Labels: documentation

#282 Slicer for small object detection
  docs/detection/tools/slicer.md
  supervision/__init__.py
  supervision/detection/core.py
  supervision/detection/tools/slicer.py
  supervision/detection/utils.py
Labels: version 0.14.0
