Repository roboflow/supervision, pull requests merged in 2024-03, with the labels that each got.

#819 New function [JSONSink] - Allowing to serialise Detections to a JSON file
  docs/detection/tools/save_detections.md
  supervision/__init__.py
  supervision/detection/tools/json_sink.py
  test/detection/test_json.py
Labels: enhancement, api:detection, api:Jsonsink

#994 Fix for #993 TypeError: 'ImageDetectionPrediction' object is not subscriptable
  cookbooks/README.md
  demo.ipynb
  docs/notebooks/quickstart.ipynb
Labels: bug

#969 fix: 🐞 update PolygonZone test and update traffic-analysis depricated codes are updated
  examples/traffic_analysis/inference_example.py
  examples/traffic_analysis/requirements.txt
  examples/traffic_analysis/ultralytics_example.py
  test/detection/test_polygonzone.py
Labels: enhancement, api:polygonzone

#996 doc: 📚 json and csv example code syntax fix
  supervision/detection/tools/csv_sink.py
  supervision/detection/tools/json_sink.py
Labels: documentation

#1006 ci: 👷 develop doc concurrency added for single run and cancel old ones
  .github/workflows/docs.yml
Labels: documentation, enhancement, github_actions

#1012 feat: 📝 static type improvement color constants and PolygonZone
  supervision/detection/tools/polygon_zone.py
  supervision/draw/color.py
Labels: bug

#1053 ci: 👷 publish pypi on branch removed
  .github/workflows/publish.yml
Labels: bug

#1062 fix Detections.get_data_item() bug (#1061)
  supervision/detection/utils.py
Labels: bug, api:detection

#1068 docs: 📚 conda and mamba installation methods added
  README.md
  docs/index.md
Labels: documentation
