Repository roboflow/supervision, pull requests merged in 2024-01, with the labels that each got.

#705 feature/extract-class-name-from-roboflow-result
  supervision/config.py
  supervision/detection/core.py
  supervision/detection/utils.py
  test/detection/test_utils.py
Labels: api:detection

#708 feature/update-label-annotator-to-respect-class-name-detection-data-field
  supervision/annotators/core.py
Labels: api:annotator

#684 ci: 👷 close dependabot warning and PR requests for min version(py38)
  .github/requirements-dev-min.txt
  .github/workflows/test-min.yml
Labels: bug, enhancement, dependencies, github_actions

#737 `fix/line-zone-trigger-returns-value-error`
  supervision/detection/line_counter.py
Labels: bug

#739 `feature/add-comments-system-powered-by-github-discussions`
  docs/annotators.md
  docs/assets.md
  docs/classification/core.md
  docs/datasets.md
  docs/detection/core.md
  docs/detection/tools/inference_slicer.md
  docs/detection/tools/line_zone.md
  docs/detection/tools/polygon_zone.md
  docs/detection/utils.md
  docs/draw/color.md
  docs/draw/utils.md
  docs/geometry/core.md
  docs/how_to/detect_and_annotate.md
  docs/how_to/evaluate_model.md
  docs/how_to/filter_detections.md
  docs/how_to/process_video.md
  docs/how_to/track_objects.md
  docs/index.md
  docs/metrics/detection.md
  docs/theme/partials/comments.html
  docs/trackers.md
  docs/utils/file.md
  docs/utils/image.md
  docs/utils/notebook.md
  docs/utils/video.md
  examples/count_people_in_zone/.gitignore
  examples/speed_estimation/.gitignore
  examples/traffic_analysis/.gitignore
Labels: documentation

#733 `fix/speed-estimation-issue-when-detections-empty`
  examples/speed_estimation/requirements.txt
  examples/speed_estimation/ultralytics_example.py
Labels: bug

#747 fix(security): 🔐 bump scipy version for memory leak vulnerability
  .github/workflows/test-min.yml
  poetry.lock
  pyproject.toml
Labels: enhancement, python, api:security

#750 fix: ✨ bump opencv version and remove upper limit
  poetry.lock
  pyproject.toml
Labels: enhancement, python

#720 Add `sv.PercentageBarAnnotator()` for confidence level bar annotation in specified position
  .gitignore
  docs/annotators.md
  poetry.lock
  pyproject.toml
  supervision/__init__.py
  supervision/annotators/core.py
Labels: documentation, enhancement, api:annotator

#696 Add Prediction Smoothing
  CONTRIBUTING.md
  docs/annotators.md
  docs/detection/core.md
  docs/detection/tools/smoother.md
  docs/how_to/evaluate_model.md
  docs/how_to/process_video.md
  docs/index.md
  mkdocs.yml
  supervision/__init__.py
  supervision/annotators/core.py
  supervision/detection/line_counter.py
  supervision/detection/tools/smoother.py
Labels: enhancement

#761 Removed '>>>' and '...' from examples and docs and improved some indentation.
  docs/annotators.md
  supervision/annotators/core.py
  supervision/assets/downloader.py
  supervision/classification/core.py
  supervision/dataset/core.py
  supervision/detection/annotate.py
  supervision/detection/core.py
  supervision/detection/tools/inference_slicer.py
  supervision/detection/utils.py
  supervision/draw/utils.py
  supervision/geometry/utils.py
  supervision/metrics/detection.py
  supervision/tracker/byte_tracker/core.py
  supervision/utils/file.py
  supervision/utils/image.py
  supervision/utils/notebook.py
  supervision/utils/video.py
Labels: documentation, enhancement, version: 0.18.0

#773 docs: 📝 readme >>>/... removed
  README.md
Labels: documentation, enhancement

#774 fix(docs): 🐞 emoji extension added for show emojis properly
  .pre-commit-config.yaml
  mkdocs.yml
Labels: bug, documentation

#770 feat: ✨ yolov8-obb support and OrientedBoxAnnotator added for obb
  docs/annotators.md
  docs/index.md
  supervision/__init__.py
  supervision/annotators/core.py
  supervision/detection/core.py
  supervision/tracker/byte_tracker/core.py
Labels: enhancement, api:annotator, api:detection

#796 docs: 📝 missing import of numpy and correct variable name in tracker section
  supervision/tracker/byte_tracker/core.py
Labels: bug, documentation

#797 small `crop_image` documentation fix
  supervision/utils/image.py
Labels: bug, documentation

#798 fix looping over detections in dataset loaders
  supervision/dataset/formats/coco.py
  supervision/dataset/formats/pascal_voc.py
  supervision/dataset/formats/yolo.py
Labels: bug, api:datasets

#802 LineZoneAnnotator make display of int/out values optional
  supervision/detection/line_counter.py
  supervision/draw/utils.py
  supervision/geometry/core.py
Labels: enhancement, good first issue, api: linezone

#815 ci: 👷 documentation build via mike for develop tag configuration
  .github/workflows/docs.yml
  mkdocs.yml
Labels: documentation, version: 0.19.0

#822 fix: 🐞 version provider typo fix
  mkdocs.yml
Labels: bug, documentation, github_actions

#828 improved communication of deprecated features
  docs/changelog.md
  mkdocs.yml
  supervision/detection/annotate.py
  supervision/detection/core.py
  supervision/draw/color.py
Labels: documentation, enhancement

#830 Update `FPSMonitor` API
  docs/deprecated.md
  pyproject.toml
  supervision/utils/video.py
Labels: enhancement, api:video
