Repository roboflow/supervision, pull requests merged in 2024-08, with the labels that each got.

#1454 Add ultralytics SAM support when using `bboxes` and `points` arguments in `SAM().predict()`
  .pre-commit-config.yaml
  supervision/detection/core.py
Labels: bug

#1458 [TriangleAnnotator, DotAnnotator] - allow customization of the contour color #1403
  supervision/annotators/core.py
Labels: enhancement, api:annotator

#1469 documentation url typo fix
  docs/how_to/track_objects.md
Labels: bug, documentation

#930 [IconAnnotator] - Add IconAnnotator to Mark Objects with Custom Icons/Images
  docs/detection/annotators.md
  supervision/__init__.py
  supervision/annotators/core.py
  supervision/utils/image.py
Labels: enhancement, api:annotator

#1459 docs: cookbook visual fix for cards and small ci doc dev changes
  .github/workflows/test-doc.yml
  CONTRIBUTING.md
  docs/javascripts/cookbooks-card.js
  docs/stylesheets/cookbooks-card.css
  docs/theme/cookbooks.html
  poetry.lock
  pyproject.toml
Labels: bug, documentation, github_actions

#1473 formatter: 🔧 improvements for pre-commit and ruff also apply minor mypy/pep fixes
  .pre-commit-config.yaml
  demo.ipynb
  poetry.lock
  pyproject.toml
  test/annotators/test_utils.py
  test/dataset/formats/test_pascal_voc.py
  test/dataset/test_core.py
  test/dataset/test_utils.py
  test/detection/test_core.py
  test/detection/test_csv.py
  test/detection/test_json.py
  test/detection/test_line_counter.py
  test/detection/test_polygonzone.py
  test/metrics/test_detection.py
  test/test_utils.py
Labels: enhancement, github_actions

#1485 fix: 🐞 poetry lock file
  poetry.lock
Labels: bug

#1494 fix(refactor): 🐞 Update deprecated usages of supervision tests to the latest version
  test/dataset/test_core.py
  test/detection/test_polygonzone.py
Labels: api:datasets, api:tests
