Repository roboflow/supervision, pull requests merged in 2024-11, with the labels that each got.

#1637 feat(ByteTrack): Allow ByteTrack to track detection without class ids
  supervision/tracker/byte_tracker/core.py
Labels: hacktoberfest-accepted

#1643 fix: 🐞 Remove lowercase conversion for unique class names in merge_class_lists function
  supervision/dataset/utils.py
Labels: bug

#1645 docs: 📝 hacktoberfest banner removed
  README.md
Labels: documentation

#1589 Feat: Added detection metadata
  supervision/detection/core.py
  supervision/detection/utils.py
  test/utils/test_internal.py
Labels: hacktoberfest-accepted

#1625 Added smart positioning (non overlapping labels) to VertexLabelAnnotator
  supervision/annotators/core.py
  supervision/detection/utils.py
  supervision/keypoint/annotators.py
Labels: enhancement, api:annotator, hacktoberfest-accepted

#1696 docs: 📝 extend supervision installation methods
  docs/index.md
Labels: documentation
