Repository roboflow/supervision, pull requests merged in 2024-10, with the labels that each got.

#1555 Add per-class counting to LineZone, create LineZoneAnnotatorMulticlass
  CODE_OF_CONDUCT.md
  docs/detection/tools/line_zone.md
  supervision/__init__.py
  supervision/detection/line_zone.py
Labels: enhancement, api: linezone

#1570 fix: 🔥 downgrade mkdocs-git-committers-plugin-2 to version 2.3.0
  .github/workflows/publish-dev-docs.yml
  .github/workflows/publish-release-docs.yml
  .github/workflows/test-doc.yml
  poetry.lock
  pyproject.toml
Labels: bug, hacktoberfest

#1571 Revert "fix: 🔥 downgrade mkdocs-git-committers-plugin-2 to version 2.3.0"
  .github/workflows/publish-dev-docs.yml
  .github/workflows/publish-release-docs.yml
  .github/workflows/test-doc.yml
  poetry.lock
  pyproject.toml
Labels: bug

#1577 Bugfix: Class-agnostic mAP
  supervision/metrics/__init__.py
  supervision/metrics/core.py
  supervision/metrics/mean_average_precision.py
Labels: hacktoberfest

#1584 ci: 👷 python3.13 ci tests and tox ver added
  .github/workflows/test.yml
  tox.ini
Labels: enhancement, hacktoberfest, github_actions, api:tests

#1591 feat: 🚀 Add default color to PolygonZoneAnnotator, drawing functions
  supervision/detection/tools/polygon_zone.py
  supervision/draw/utils.py
Labels: bug, enhancement, hacktoberfest

#1595 feat: 🚀 python3.13 support for poetry and library
  .github/workflows/poetry-test.yml
  poetry.lock
  pyproject.toml
Labels: enhancement, hacktoberfest

#1618 feat(ByteTrack): Allow ByteTrack to track detection without class ids
  supervision/tracker/byte_tracker/core.py
Labels: hacktoberfest-accepted
