Repository roboflow/supervision, pull requests merged in 2024-02, with the labels that each got.

#827 [ByteTrack] - add a method to reset the state of the tracker
  supervision/tracker/byte_tracker/basetrack.py
  supervision/tracker/byte_tracker/core.py
Labels: enhancement, api:tracker, Q1.2024

#829 docs: ✨ fix url and coc and contributing.md, pythonic features of docs enabled, relative urls added.
  README.md
  docs/annotators.md
  docs/changelog.md
  docs/code_of_conduct.md
  docs/contributing.md
  docs/how_to/detect_and_annotate.md
  docs/how_to/track_objects.md
  docs/index.md
  docs/license.md
  docs/metrics/detection.md
  examples/README.md
  mkdocs.yml
  supervision/annotators/core.py
  supervision/classification/core.py
  supervision/detection/line_counter.py
  supervision/detection/tools/smoother.py
Labels: documentation, enhancement

#843 docs(fix): 🐞📝 relative path fix for mike
  docs/changelog.md
  mkdocs.yml
Labels: bug

#845 [LineZone] - flip in/out line crossing directions #838
  supervision/detection/line_counter.py
Labels: bug

#847 [NMS] - add segmentation models support
  docs/detection/utils.md
  supervision/__init__.py
  supervision/detection/core.py
  supervision/detection/utils.py
  test/detection/test_utils.py
Labels: api:detection

#860 docs(page): 🚀 Supervision Cookbook
  .github/workflows/docs.yml
  .gitignore
  README.md
  demo.ipynb
  docs/assets.md
  docs/changelog.md
  docs/cookbooks.md
  docs/how_to/detect_and_annotate.md
  docs/index.md
  docs/javascripts/cookbooks-card.js
  docs/javascripts/init_kapa_widget.js
  docs/javascripts/zoominfo.js
  docs/notebooks/quickstart.ipynb
  docs/stylesheets/cookbooks-card.css
  docs/stylesheets/extra.css
  docs/theme/cookbooks.html
  docs/theme/main.html
  mkdocs.yml
  poetry.lock
  pyproject.toml
Labels: documentation, enhancement, doc:sv:notebooks

#862 docs(fix): 🐞📝 MKDOCS_GIT_COMMITTERS_APIKEY value added
  .github/workflows/docs.yml
Labels: bug

#863 docs(fix): 🐞📝 MKDOCS_GIT_COMMITTERS_APIKEY fix attempt v2
  .github/workflows/docs.yml
  mkdocs.yml
Labels: bug

#865 cookbooks page HTML optimisation + CSS update
  docs/javascripts/cookbooks-card.js
  docs/stylesheets/cookbooks-card.css
  docs/theme/cookbooks.html
Labels: doc:sv:notebooks

#868 [Cookbooks] - Improved functionality of cookbook cards
  docs/javascripts/cookbooks-card.js
  docs/stylesheets/cookbooks-card.css
  docs/theme/cookbooks.html
Labels: doc:sv:notebooks

#869 [Cookbooks] - Count Objects Crossing the Line
  docs/notebooks/annotate-video-with-detections.ipynb
  docs/notebooks/download-supervision-assets.ipynb
  docs/notebooks/object-tracking.ipynb
Labels: doc:sv:notebooks

#882 `LineZone`, `LineZoneAnnotator` documentation improvements
  docs/detection/tools/line_zone.md
  docs/detection/tools/polygon_zone.md
  docs/detection/tools/smoother.md
  supervision/__init__.py
  supervision/detection/line_zone.py
  supervision/utils/video.py
Labels: documentation

#884 `CONTRIBUTING.md` updates.
  CONTRIBUTING.md
Labels: documentation

#901 [Detections] - from_inference should include 'class_name' key in Detections.data even if result is empty #837
  supervision/detection/core.py
Labels: bug, api:detection

#905 Add Support for Center Left,Right Text Position for LabelAnnotator
  supervision/annotators/core.py
Labels: enhancement, api:annotator

#870 docs: 📝 h1 title Home removed from index.md
  docs/index.md
  docs/theme/index.html
Labels: documentation

#955 fix(docs): 🐞 PercentageBarAnnotator example doc code usage fixed
  supervision/annotators/core.py
Labels: bug, documentation

#944 Fix smoother removing tracking_id from detections
  supervision/detection/tools/smoother.py
Labels: api:detection

#942 feat(PolygonZoneAnnotator): ✨ make display of zone label optional default is true
  supervision/detection/tools/polygon_zone.py
Labels: enhancement, api:annotator

#961 ci: 👷 remove duplicated publish tag regex
  .github/workflows/publish.yml
Labels: github_actions

#886 [ByteTrack] - change the names and documenting input arguments #787
  supervision/tracker/byte_tracker/core.py
  supervision/utils/internal.py
Labels: documentation, enhancement

#963 feat(ImageType): 🚀 sv.plot_images_grid and sv.plot_image can accept ImageType
  supervision/annotators/utils.py
  supervision/utils/notebook.py
Labels: bug

#907 Add a cookbook about alignment evaluation
  docs/notebooks/evaluating-alignment-of-text-to-image-diffusion-models.ipynb
  docs/theme/cookbooks.html
Labels: doc:sv:notebooks

#964 fix: 🐞 evaluating-alignment-of-text-to-image-diffusion-model widget fix for docs to render
  docs/notebooks/evaluating-alignment-of-text-to-image-diffusion-models.ipynb
Labels: bug

#965 feat: 📚 add docs test workflow
  .github/workflows/test-doc.yml
Labels: github_actions
