Repository roboflow/supervision, pull requests merged in 2024-07, with the labels that each got.

#1317 fix: 🐞 skip broken docutils package, revert numpy version lock
  poetry.lock
  pyproject.toml
Labels: bug

#1336 docs: revise and restructure CONTRIBUTING.md
  CONTRIBUTING.md
  pyproject.toml
Labels: documentation

#1310 feat: 🚀 Keypoint support for detectron2
  supervision/keypoint/core.py
  supervision/validators/__init__.py
Labels: enhancement, api:keypoints

#1372 fix `from_matplotlib` when Matplotlib colormaps does not provide `colors` property
  supervision/draw/color.py
Labels: bug, api:annotator

#1374 fix incorrect annotators docstring
  supervision/annotators/core.py
Labels: bug, api:annotator

#1380 fix: 🐞 poetry numpy version has been set based on python version
  poetry.lock
  pyproject.toml
Labels: bug

#520 Add dataset processing documentation
  docs/how_to/process_datasets.md
  mkdocs.yml
Labels: documentation

#1400 Fix typo in RichLabelAnnotator docs
  docs/detection/annotators.md
Labels: bug, documentation
